---
- name: Create group
  ansible.builtin.group:
    name: "{{ group_name }}"
    state: present

- name: Create users
  ansible.builtin.user:
    name: "{{ item }}"
    groups: "{{ group_name }}"
    state: present
    shell: /bin/bash
  loop: "{{ users }}"

- name: Set permissions for users
  ansible.builtin.file:
    path: "{{ permission_path_base }}/{{ item }}"
    owner: "{{ item }}"
    group: "{{ group_name }}"
    mode: "{{ permission_mode }}"
  loop: "{{ users }}"
