---
- name: Setup CLI, Docker, and HTTPD
  hosts: "{{ target_host }}"
  become: yes

  vars_prompt:
    - name: "target_host"
      prompt: "Enter the target host (use hostname or IP address):"
      private: no
  roles:
    - role: package_install/cli
    - role: package_install/docker
      vars_files:
        - roles/package_install/docker/vars/vars.yml
    - role: package_install/httpd
