---
- name: Setup CLI, Docker, and HTTPD
  hosts: "{{ target_host }}"
  become: yes

  vars_prompt:
    - name: "target_host"
      prompt: "Enter the target host (use hostname or IP address):"
      private: no
  roles:
    - role: package_install
  
  vars_files:
    - roles/package_install/vars/vars.yml
