---
- name: Build Docker image
  docker_image:
    path: "{{ docker_build_context }}"
    name: "{{ image_name }}"
    tag: "{{ image_tag }}"
    state: present

- name: Run Docker container from image
  docker_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}:{{ image_tag }}"
    state: started
    restart_policy: always
    exposed_ports:
      - "8080"
    published_ports:
      - "8080:8080"
