---
- name: Pull Docker image from Docker Hub
  docker_image:
    name: "{{ image_name }}"
    tag: "{{ image_tag }}"
    source: pull
    state: present

- name: Run Docker container from pulled image
  docker_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}:{{ image_tag }}"
    state: started
    restart_policy: always
    exposed_ports:
      - "8080"
    published_ports:
      - "8080:8080"
