 - name: Install lvm2 dependency
      package:
        name: lvm2
        state: present

    - name: task for creating volume group
      lvg:
          vg: "{{vg_name}}"
          pvs: /dev/{{command_output.stdout}}
          pesize: 16

    - name: task for creating logical volume
      lvol:
          vg: "{{vg_name}}"
          lv: "{{lv_name}}"
          size: "{{size}}"
          force: yes

    - name: Create directory mountpoint if does not exist
      file:
        path: "{{dir}}"
        state: directory
        mode: '0777'

    - name: format the xfs filesystem
      filesystem:
        fstype: "{{ftype}}"
        dev: /dev/{{vg_name}}/{{lv_name}}

    - name: mount the lv on mountpoint
      mount:
        src: /dev/{{vg_name}}/{{lv_name}}
        fstype: "{{ftype}}"
        state: mounted
        path: "{{ dir }}"
