---
- name: Install HTTPD (Apache)
  package:
    name: "{{ httpd_package }}"
    state: present

- name: Ensure HTTPD is enabled and running
  service:
    name: "{{ httpd_service }}"
    state: started
    enabled: true
